<?php

/**
 * Settings Custom Fields
 *
 * @link       ajardiah.dev
 * @since      1.0.0
 *
 * @package    Builders_Hub
 * @subpackage Builders_Hub/includes
 */

/**
 * Fired during plugin activation.
 *
 * This class defines all code necessary to run during the plugin's activation.
 *
 * @since      1.0.0
 * @package    Builders_Hub
 * @subpackage Builders_Hub/includes
 * @author     AJ Jardiah Jr <ajardiahjr@gmail.com>
 */

namespace Inc\Base\Fields;
use Inc\Base\BaseController;

class CommunityFields extends BaseController
{
    public function register()
    {
        add_action( 'init', array( $this, 'createCommunityFields' ) );
    }

    public static function createCommunityFields()
    {
        if( function_exists('acf_add_local_field_group') ):

            acf_add_local_field_group(array(
                'key' => 'group_621e751adcdac',
                'title' => 'Community Information',
                'fields' => array(
                    array(
                        'key' => 'field_621e76a9e0be1',
                        'label' => 'Community Information',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621fc4207e179',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621e75b13b2cb',
                        'label' => 'Community Name',
                        'name' => 'community_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'required_message' => '',
                        'default_value' => '',
                        'placeholder' => 'Community Name',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621fc42d7e17a',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621f8744fa2e6',
                        'label' => 'Community ID',
                        'name' => 'community_id',
                        'type' => 'number',
                        'instructions' => 'Number assigned by you for that community. Unique identification number among all of the builder’s subdivisions.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Community ID',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621fc4387e17b',
                        'label' => '(Column Endpoint)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'endpoint' => 1,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                        'acfe_field_group_condition' => 0,
                        'columns' => '6/12',
                        'border' => '',
                    ),
                    array(
                        'key' => 'field_621f847a1a660',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621f94a8051ff',
                        'label' => 'Community Type',
                        'name' => 'community_type',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Gated' => 'Gated',
                            'Adult' => 'Adult',
                            'Condo Only' => 'Condo Only',
                            'Age Restricted' => 'Age Restricted',
                            'Urban' => 'Urban',
                            'Townhomes' => 'Townhomes',
                            'Green' => 'Green',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'max' => '',
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'allow_custom' => 0,
                        'search_placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'acfe_field_group_condition' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_621f8efed9c48',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621e77c60b365',
                        'label' => 'Status',
                        'name' => 'status',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Select' => 'Select',
                            'Active' => 'Active',
                            'Sold' => 'Sold',
                            'ComingSoon' => 'Coming Soon',
                            'Closeout' => 'CloseOut',
                            'GrandOpening' => 'Grand Opening',
                            'Excluded' => 'Excluded',

                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'max' => '',
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'allow_custom' => 0,
                        'search_placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'acfe_field_group_condition' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_621f8ee064008',
                        'label' => '(Column Endpoint)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'endpoint' => 1,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                        'acfe_field_group_condition' => 0,
                        'columns' => '6/12',
                        'border' => '',
                    ),
                    array(
                        'key' => 'field_621f86fe82abd',
                        'label' => '(Column 4/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '4/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621e81ccae741',
                        'label' => 'SqFt',
                        'name' => 'sqft',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'table',
                        'acfe_group_modal' => 1,
                        'acfe_group_modal_close' => 0,
                        'acfe_group_modal_button' => 'Add - Edit SqFt',
                        'acfe_group_modal_size' => 'medium',
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621e81e1ae742',
                                'label' => 'Min',
                                'name' => 'comm_min_SqFt',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'Low',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                            array(
                                'key' => 'field_621e81ffae743',
                                'label' => 'Max',
                                'name' => 'comm_max_sqft',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'High',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621f84f55523d',
                        'label' => '(Column 4/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '4/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621e998f2fb1b',
                        'label' => 'Price',
                        'name' => 'comm_price',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'table',
                        'acfe_group_modal' => 1,
                        'acfe_group_modal_close' => 0,
                        'acfe_group_modal_button' => 'Add - Edit Pricing',
                        'acfe_group_modal_size' => 'medium',
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621e998f2fb1c',
                                'label' => 'Min',
                                'name' => 'comm_min_price',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'Low',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                            array(
                                'key' => 'field_621e998f2fb1d',
                                'label' => 'Max',
                                'name' => 'comm_max_price',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'High',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621f8cc1cb32a',
                        'label' => '(Column 4/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '4/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621f8d4c0fcad',
                        'label' => 'Featured Community',
                        'name' => 'featured_community_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_group_modal' => 1,
                        'acfe_group_modal_close' => 0,
                        'acfe_group_modal_button' => 'Add Featured Community',
                        'acfe_group_modal_size' => 'small',
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621f8d700fcae',
                                'label' => 'Featured Community',
                                'name' => 'featured_community',
                                'type' => 'true_false',
                                'instructions' => 'Checkbox to featured community on the homepage “featured showcase Community” section.',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => 'Yes',
                                'ui_off_text' => 'No',
                                'acfe_field_group_condition' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621f88cc32454',
                        'label' => '(Column Endpoint)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'endpoint' => 1,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                        'acfe_field_group_condition' => 0,
                        'columns' => '6/12',
                        'border' => '',
                    ),
                    array(
                        'key' => 'field_621e99ea04a3c',
                        'label' => '',
                        'name' => 'comm_description_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62265c9b4525b',
                                'label' => '',
                                'name' => 'comm_headline',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'Headline',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                            array(
                                'key' => 'field_62265cb14525c',
                                'label' => '',
                                'name' => 'comm_description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'Description',
                                'maxlength' => '',
                                'rows' => 6,
                                'new_lines' => 'wpautop',
                                'acfe_textarea_code' => 0,
                                'acfe_field_group_condition' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621eb76e2657a',
                        'label' => 'Location',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621eb78c2657b',
                        'label' => 'Address',
                        'name' => 'comm_address',
                        'type' => 'text',
                        'instructions' => 'Street address',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'required_message' => '',
                        'default_value' => '',
                        'placeholder' => 'Street Address',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f8f3ebafa9',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => array(
                            0 => 'fields',
                        ),
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621eb7de2657c',
                        'label' => 'City',
                        'name' => 'comm_city',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'required_message' => '',
                        'default_value' => '',
                        'placeholder' => 'City',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f8f74bafad',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => array(
                            0 => 'fields',
                        ),
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621eb8032657d',
                        'label' => 'County',
                        'name' => 'comm_county',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'County',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f85035523e',
                        'label' => '(Column Endpoint)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'endpoint' => 1,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                        'acfe_field_group_condition' => 0,
                        'columns' => '6/12',
                        'border' => '',
                    ),
                    array(
                        'key' => 'field_621f8fdb3dae2',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => array(
                            0 => 'fields',
                        ),
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621eb8532657e',
                        'label' => 'State',
                        'name' => 'comm_state',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'required_message' => 'State is required',
                        'default_value' => '',
                        'placeholder' => 'State',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f8fea3dae4',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => array(
                            0 => 'fields',
                        ),
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621eb8872657f',
                        'label' => 'Postal Code',
                        'name' => 'comm_postal_code',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'required_message' => 'Postal Code is required',
                        'default_value' => '',
                        'placeholder' => 'Postal Code',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f8fe33dae3',
                        'label' => '(Column Endpoint)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'endpoint' => 1,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                        'acfe_field_group_condition' => 0,
                        'columns' => '6/12',
                        'border' => '',
                    ),
                    array(
                        'key' => 'field_621eb9db6a684',
                        'label' => 'Geolocation',
                        'name' => 'latitude_longitude',
                        'type' => 'group',
                        'instructions' => '<a href="https://www.latlong.net" target="_blank">Find Geocoordinates</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'table',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621eba466a685',
                                'label' => 'Latitude',
                                'name' => 'latitude',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'required_message' => 'Latitude is required',
                                'default_value' => '',
                                'placeholder' => '38.8888',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                            array(
                                'key' => 'field_621eba896a686',
                                'label' => 'Longitude',
                                'name' => 'longitude',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'required_message' => 'Longitude is required',
                                'default_value' => '-94.88',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621f911429fcf',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => array(
                            0 => 'fields',
                        ),
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621f906b86b36',
                        'label' => 'Directions',
                        'name' => 'Comm_directions_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'table',
                        'acfe_group_modal' => 1,
                        'acfe_group_modal_close' => 0,
                        'acfe_group_modal_button' => 'Add - Edit Directions Text',
                        'acfe_group_modal_size' => 'medium',
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621f908386b37',
                                'label' => 'Directions',
                                'name' => 'Comm_directions_text',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 6,
                                'new_lines' => 'wpautop',
                                'acfe_textarea_code' => 0,
                                'acfe_field_group_condition' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621f912429fd1',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => array(
                            0 => 'fields',
                        ),
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_621ec18eab192',
                        'label' => 'Out of Community Sales Office',
                        'name' => 'out_of_community_sales_office',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Yes',
                        'ui_off_text' => 'No',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_62265c5ddd3a1',
                        'label' => '(Column Endpoint)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'endpoint' => 1,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                        'acfe_field_group_condition' => 0,
                        'columns' => '6/12',
                        'border' => '',
                    ),
                    array(
                        'key' => 'field_621ec1ff7e01f',
                        'label' => 'Out of Community Sales Office',
                        'name' => 'out_of_community_sales_office',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_621ec18eab192',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_group_modal' => 1,
                        'acfe_group_modal_close' => 0,
                        'acfe_group_modal_button' => 'Edit - Add Out of Community Sales Office Address',
                        'acfe_group_modal_size' => 'medium',
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621ec2347e020',
                                'label' => 'Out of Community Address',
                                'name' => 'out_of_community_address',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'Street Address',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                            array(
                                'key' => 'field_621ec287b87ee',
                                'label' => 'Out of Community City',
                                'name' => 'out_of_community_city',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'City',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                            array(
                                'key' => 'field_621ec2b1b87ef',
                                'label' => 'Out of Community County',
                                'name' => 'out_of_community_county',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'County',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                            array(
                                'key' => 'field_621ec2ceb87f0',
                                'label' => 'Out of Community State',
                                'name' => 'out_of_community_state',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'State',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                            array(
                                'key' => 'field_621ec2e3b87f1',
                                'label' => 'Out of Community Postal Code',
                                'name' => 'out_of_community_postal_code',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'Postal Code',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                            array(
                                'key' => 'field_621f92ed048d2',
                                'label' => '',
                                'name' => 'lat_lng_out_community',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'table',
                                'acfe_seamless_style' => 0,
                                'acfe_group_modal' => 0,
                                'acfe_field_group_condition' => 0,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_621f930f048d3',
                                        'label' => 'Latitude',
                                        'name' => 'latitude_out_of_community_sf',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'required_message' => '',
                                        'default_value' => '',
                                        'placeholder' => '89.009',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'acfe_field_group_condition' => 0,
                                    ),
                                    array(
                                        'key' => 'field_621f9346048d4',
                                        'label' => 'Longitude',
                                        'name' => 'longitude_out_of_community_sf',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'required_message' => '',
                                        'default_value' => '',
                                        'placeholder' => '-98.003',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'acfe_field_group_condition' => 0,
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621f9643b098c',
                        'label' => 'Photos',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f959db098b',
                        'label' => 'Photos',
                        'name' => 'gallery',
                        'type' => 'gallery',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'required_message' => 'Gallery MUST have at least 1 photo.',
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'insert' => 'append',
                        'library' => 'all',
                        'min' => 1,
                        'max' => '',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f975938df3',
                        'label' => 'Community Map',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f96cd38df1',
                        'label' => 'Community Map',
                        'name' => 'community_map_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_group_modal' => 1,
                        'acfe_group_modal_close' => 0,
                        'acfe_group_modal_button' => 'Add - Edit Community Map',
                        'acfe_group_modal_size' => 'medium',
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621f971b38df2',
                                'label' => 'Community Map',
                                'name' => 'community_map',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'uploader' => '',
                                'acfe_thumbnail' => 0,
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'acfe_field_group_condition' => 0,
                                'library' => 'all',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621f985a83055',
                        'label' => 'Video',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f986b83056',
                        'label' => 'Video',
                        'name' => 'video_comm',
                        'type' => 'oembed',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'width' => '',
                        'height' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f98f963914',
                        'label' => 'Schools',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f990f63915',
                        'label' => 'Schools',
                        'name' => 'school_comm_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_group_modal' => 1,
                        'acfe_group_modal_close' => 0,
                        'acfe_group_modal_button' => 'Add - Edit Schools',
                        'acfe_group_modal_size' => 'medium',
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621f99fcb17bf',
                                'label' => 'Schools',
                                'name' => 'Comm_school_listing',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'acfe_repeater_stylised_button' => 0,
                                'collapsed' => 'field_621f9a35b17c0',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'block',
                                'button_label' => 'Add School',
                                'acfe_field_group_condition' => 0,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_621f9a35b17c0',
                                        'label' => 'School District',
                                        'name' => 'school_district',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'acfe_field_group_condition' => 0,
                                    ),
                                    array(
                                        'key' => 'field_621f9a54b17c1',
                                        'label' => 'Elementary School',
                                        'name' => 'elementary_school_comm',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'acfe_field_group_condition' => 0,
                                    ),
                                    array(
                                        'key' => 'field_621f9a5db17c2',
                                        'label' => 'Middle School',
                                        'name' => 'middle_school_comm',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'acfe_field_group_condition' => 0,
                                    ),
                                    array(
                                        'key' => 'field_621f9a67b17c3',
                                        'label' => 'High School',
                                        'name' => 'high_school_comm',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'acfe_field_group_condition' => 0,
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621f9c148be64',
                        'label' => 'Plans',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f9b6b05940',
                        'label' => '',
                        'name' => 'plans_community_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_seamless_style' => 1,
                        'acfe_group_modal' => 0,
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621f9b8c05941',
                                'label' => 'Plans',
                                'name' => 'plans_comm',
                                'type' => 'relationship',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array(
                                    0 => 'plans',
                                ),
                                'taxonomy' => '',
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'elements' => array(
                                    0 => 'featured_image',
                                ),
                                'min' => '',
                                'max' => '',
                                'return_format' => 'object',
                                'acfe_add_post' => 1,
                                'acfe_edit_post' => 1,
                                'acfe_bidirectional' => array(
                                    'acfe_bidirectional_enabled' => '0',
                                ),
                                'acfe_field_group_condition' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621f9d7aa4e5f',
                        'label' => 'Homes',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f9d90a4e60',
                        'label' => '',
                        'name' => 'homes_comm_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_seamless_style' => 1,
                        'acfe_group_modal' => 0,
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621f9d90a4e61',
                                'label' => 'Available Homes',
                                'name' => 'available_homes_comm',
                                'type' => 'relationship',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array(
                                    0 => 'homes',
                                ),
                                'taxonomy' => '',
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'elements' => array(
                                    0 => 'featured_image',
                                ),
                                'min' => '',
                                'max' => '',
                                'return_format' => 'object',
                                'acfe_add_post' => 1,
                                'acfe_edit_post' => 1,
                                'acfe_bidirectional' => array(
                                    'acfe_bidirectional_enabled' => '0',
                                ),
                                'acfe_field_group_condition' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621f9f41e3b40',
                        'label' => 'Custom Fields',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_621f9f830f2dd',
                        'label' => '',
                        'name' => 'custom_fields_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_group_modal' => 1,
                        'acfe_group_modal_close' => 0,
                        'acfe_group_modal_button' => 'Add - Edit Brochure',
                        'acfe_group_modal_size' => 'medium',
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621f9fa50f2de',
                                'label' => 'Downloadable Brochure',
                                'name' => 'downloadable_brochure',
                                'type' => 'file',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'uploader' => '',
                                'return_format' => 'array',
                                'min_size' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'upload_folder' => '',
                                'multiple' => 0,
                                'max' => '',
                                'acfe_field_group_condition' => 0,
                                'library' => 'all',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621fa0c8f8424',
                        'label' => '',
                        'name' => 'banner_announcements_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621fa0e9f8425',
                                'label' => 'Banner Announcements',
                                'name' => 'banner_announcements',
                                'type' => 'true_false',
                                'instructions' => 'Add custom Announcement to the community Search page Card',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => 'Enable',
                                'ui_off_text' => 'Disable',
                                'acfe_field_group_condition' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621fa199fb18c',
                        'label' => '',
                        'name' => 'enable_banner_announcement_group',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_621fa0e9f8425',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'acfe_field_group_condition' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_621fa1b8fb18e',
                                'label' => 'Custom Banner Announcement',
                                'name' => 'add_custom_banner_announcement',
                                'type' => 'text',
                                'instructions' => 'A custom message will be appear Card of the community Search page',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'New Community Coming Fall 2023',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'acfe_field_group_condition' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_621f89446adb1',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'communities',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'acf_after_title',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'tooltip',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'acfe_autosync' => '',
                'acfe_form' => 0,
                'acfe_display_title' => '',
                'acfe_meta' => '',
                'acfe_note' => '',
            ));

        endif;

    }

}